name: flutter_sholat_doa
description: "A new Flutter project."
publish_to: "none"

version: 1.0.2+3

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.0
  just_audio: ^0.9.36
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1 # ← tambahan baru

flutter_launcher_icons: # ← tambahan baru
  android: true
  ios: false
  image_path: "assets/images/playstore.png" # ← path icon kamu

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/menu/
